version: '3.9'

services:
  maven:
    build: .
    container_name: mavencont111
    ports:
      - "3008:3000"

  mysql:
    image: mysql:8
    container_name: mysqlcont111
    environment:
      - MYSQL_ROOT_PASSWORD=pass123
    ports:
      - "8083:3306"
    volumes:
      - appdata111:/var/lib/mysql

volumes:
  appdata111: